language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 src/ test/
  - phpunit --coverage-clover build/logs/clover.xml
