language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer install
  - test/server_start.sh

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

after_script:
- test/server_stop.sh
